country_code = ""  # e.g. "us"

[api]
auth_credentials_storage_base_url = ""
units_storage_base_url = ""

[employees]
blacklist = []

[message_queue]
url = "amqp://127.0.0.1:5672"

[telegram]
bot_token = ""
goretsky_band_chat_id = 0
